### ISSUE TITLE
partial not expected behavior

### ISSUE THREAD

**Issue by jaysneg** [amberframework/amber#790] opened 2018-05-14 23:50 UTC
### Description
if create subfolder at layouts and copy there files: _nav.slang and application.slang
and change at layouts/portal/application.slang path of render:
== render(partial: "layouts/portal/_nav.slang")

appears error

### Steps to Reproduce

1. copy application.slang and _nav.slang to folder at layouts
2. try to render partial _nav.slang:
== render(partial: "layouts/portal/_nav.slang")

**Expected behavior:** it will render partial 

**Actual behavior:** Shows error

**Reproduces how often:** always

### Versions

Amber 0.7.2

### Additional Information

it works in this way 

== render(partial: "portal/_nav.slang", path: "src/views/layouts/")

**Comment by faustinoaq** [comment] 2018-05-15 00:41
Hi @jaysneg Thank for report this issue :+1: 

Can you share us the error output using a [gist](https://gist.github.com/)? :sweat_smile:

**Comment by elorest** [comment] 2018-05-15 01:13
This isn't technically a bug but it might be a good place to discuss expected behavior. 

Currently if there are more than 2 parts in the path it will assume the root is your project root instead of `src/views`. 

For instance this would work: `render(partial: "src/views/layouts/tmp/_nav.slang")` as would `render(partial: "specs/samples/views/layouts/tmp/_nav.slang")`

`render(partial: "layouts/_nav.slang")` works because there are only 2 parts.

It might be better to only use the `path:` option to set other paths instead of defaulting to that for longer path names.

This would be as simple as getting rid of this conditional in render.cr and making sure the tests still pass.

```cr
    private macro render_template(filename, path = "src/views")
      {% if filename.id.split("/").size > 2 %}
        Kilt.render("{{filename.id}}")
      {% else %}
        Kilt.render("#{{{path}}}/{{filename.id}}")
      {% end %}
    end
```

**Comment by elorest** [comment] 2018-05-15 01:14
I could probably find time to work on that tonight if desired.

**Comment by jaysneg** [comment] 2018-05-15 07:32
jaysneg/gist:c5bd12aef52531b84d4647e8074b17ba

**Comment by shobhitic** [comment] 2018-06-25 01:13
Looks like this has been fixed. Should we close it?

**Closed** 2018-10-14 03:28 UTC
Labels: kind:bug, status:discussion, status:help-wanted
