### ISSUE TITLE
[Router] Allow posting array of fields from form

### ISSUE THREAD

**Issue by imdrasil** [amberframework/amber#675] opened 2018-03-07 08:59 UTC
### Description

As a developer
I would like to get an opportunity to submit array of values.

### Steps to Reproduce

From template:

```html
<form method="post" action="/user">
<!-- ... -->
<input type="checkbox" value="admin" name="role[]">
<input type="checkbox" value="owner" name="role[]">
</form>
```

Controller code:

```crystal
def create
  user_params["role"] # ["admin", "owner"]
end
```

**Comment by robacarp** [comment] 2018-03-07 20:13
@eliasjpr is this different from the updates to params that recently merged in?

**Comment by eliasjpr** [comment] 2018-03-07 20:44
@robacarp no

@imdrasil you have to use  user_params.fetch_all?("role")

Duplicate of https://github.com/amberframework/amber/issues/592

**Comment by eliasjpr** [comment] 2018-04-18 11:18
Closing this issue since this was address with #592

**Closed by eliasjpr** 2018-04-18 11:18 UTC
Labels: kind:feature, status:duplicate
