### ISSUE TITLE
Homebrew MacOS install issues

### ISSUE THREAD

**Issue by BrunoQuaresma** [amberframework/amber#448] opened 2017-12-15 16:26 UTC
### Description

I tried to install the MacOs version as the doc says.

```bash
brew tap amberframework/amber
Updating Homebrew...
==> Tapping amberframework/amber
Cloning into '/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb
403 Forbidden
Error: Cannot tap amberframework/amber: invalid syntax in tap!
```
After those errors I tried to run a `brew doctor` but everything is fine.

```bash
brew doctor
Your system is ready to brew.
```
I don't have any idea about what is happening, so any help is very welcome.

**Comment by BrunoQuaresma** [comment] 2017-12-15 16:37
I can do it using the Linux: Source instructions. Maybe it can be in a general topic instead to be inside of Linux.

```
curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
cd amber-stable/
shards install
make install
```

**Comment by eliasjpr** [comment] 2017-12-19 17:03
@BrunoQuaresma can you try `brew tap amberframework/amber/amber` instead. We have just submitted the `amber` formula to homebrew repo in hopes to have an official formula instead of a `tap` formula. See https://github.com/Homebrew/homebrew-core/pull/21895

**Comment by elorest** [comment] 2017-12-19 17:10
@eliasjpr `brew install amberframework/amber/amber` automatically taps `amberframework/amber` first.

@BrunoQuaresma As I said before hit me up on gitter and I'm willing to do a screenshare to help solve this for you.

**Comment by elorest** [comment] 2017-12-19 17:14
@BrunoQuaresma I believe I solved your issue. Install latest XCode and then run `xcode-select --install` in terminal.

**Comment by eliasjpr** [comment] 2017-12-22 14:25
@BrunoQuaresma we would like to know if you were able to  resolve the issue. We have updated the homebrew formula and the tap repo. 

We recommend for you to try once more: 

```bash
brew tap amberframework/amber
brew install amberframework/amber
```

Or perform an installation from source: 

```bash
git clone git@github.com:amberframework/amber.git
cd amber/
shards install
make
```

If you continue experiencing this issue please feel free to reopen. We are closing this for now since we cannot reproduce it.

**Closed by eliasjpr** 2017-12-22 14:25 UTC
