### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by kalicki** [amberframework/amber#486] opened 2018-01-06 17:13 UTC
REST or GraphQL or Hybrid?
Trend in this new year is the migration of great webservices to GraphQL, it would be interesting to explore this in Amber. Native or separate lib.

Idea:
http://graphql-ruby.org
https://github.com/ziprandom/graphql-crystal by @ziprandom

_A feature that would be very interesting_

**Comment by eliasjpr** [comment] 2018-01-06 18:40
This is duplicate of https://github.com/amberframework/amber/issues/265

**Closed** 2018-01-06 19:28 UTC
Labels: duplicate
