### ISSUE TITLE
initial app migration errors (folder missing; then Index out of bounds)

### ISSUE THREAD

**Issue by drhuffman12** [amberframework/amber#411] opened 2017-11-23 06:25 UTC
### Description

The initial app migration errors out (folder missing; then Index out of bounds).

Follow-up for [#387](https://github.com/amberframework/amber/issues/387).

### Steps to Reproduce

I re-installed Amber w/ the latest version (i.e.: `git pull origin master -f` in the amber folder and proceed w/ the other install steps.)

When I try to create an Amber app (db of pg or sqlite), build the container, and then `docker-compose up`, I get an error about the `db/migrations` folder missing. I add it in and then I get an error like the following error:

```sh
$ docker-compose up
Pulling mail (drujensen/mailcatcher:latest)...
latest: Pulling from drujensen/mailcatcher
cd0a524342ef: Pull complete
e39c3ffe4133: Pull complete
85334a7c2001: Pull complete
4c546d9d6a84: Pull complete
dd2ea17fcd18: Pull complete
9a1750ae4da9: Pull complete
23abf7d3a194: Pull complete
d7034d3958e1: Pull complete
8c45d0bb8c15: Pull complete
ca4a1990f80f: Pull complete
5656f3f9dfbd: Pull complete
234df2ab23da: Pull complete
aa7d88bbb5a3: Pull complete
6a0829102619: Pull complete
0d1f9265a76d: Pull complete
82896657a932: Pull complete
30a0511bf151: Pull complete
f1f49f651b08: Pull complete
a337096d1665: Pull complete
33b1fa2e711b: Pull complete
Digest: sha256:19f649859f496cd9ccf993894dd7365428ec3305d4ac3bccaabb7730a8695df1
Status: Downloaded newer image for drujensen/mailcatcher:latest
Creating exampleappamber_mail_1 ... 
Creating exampleappamber_mail_1
Creating exampleappamber_web_1 ... 
Creating exampleappamber_migrate_1 ... 
Creating exampleappamber_migrate_1
Creating exampleappamber_mail_1 ... done
Creating exampleappamber_web_1 ... done
Creating exampleappamber_app_1 ... done
Attaching to exampleappamber_migrate_1, exampleappamber_mail_1, exampleappamber_web_1, exampleappamber_app_1
migrate_1  | Index out of bounds
exampleappamber_migrate_1 exited with code 1
mail_1     | Starting MailCatcher
...
```

Checking the logs, I see:

```sh
$ docker-compose logs migrate
Attaching to exampleappamber_migrate_1
migrate_1  | Index out of bounds
```

**Expected behavior:** [What you expect to happen]

The `db/migrations` folder should exist in the generated folders; OR, it should be auto-generated when the migrations run.

**Actual behavior:** [What actually happens]

(See above.)

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always; See above.

### Versions

```sh
  $ crystal --version
  Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

  $ shards --version
  Shards 0.7.1 (2017-07-13)

  $ amber --version
  Amber CLI (amberframework.org) - v0.3.6
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by faustinoaq** [comment] 2017-11-23 15:25
@drhuffman12 I'm wondering Why this is happening?

As far as I know migrations folderare created automatically when you use `amber generate` command

@drujensen @elorest Any thoughts?

**Comment by drujensen** [comment] 2017-11-23 17:17
@drhuffman12 thanks for reporting this.  The directory is not created unless you generate a migration. Can you confirm that you generated a migration or a model?

If not, the `migrate` should fail gracefully. If yes, we have a bigger problem.

**Comment by elorest** [comment] 2017-11-23 18:34
I'm unable to replicate this error with latest master. 

1. I ran make for amber master.
1. Created new project with `amber new mastermake --deps`
1. cd'd in and ran `docker-compose up` => It worked!
1. exited and generated scaffolding. Ran `docker-compose up` and it also worked.

Happy Thanks Giving!

**Comment by drujensen** [comment] 2017-11-23 18:53
@elorest thanks for testing. 

@drhuffman12 I think this is expected behavior.  If you never created a model or migration, the `migrate` container should fail gracefully with the error since there are no migrations to run.  Once you create a model, the `migrate` will run the migration scripts correctly.

You can remove the `migrate` docker container from the `docker-compose.yml` if you are not using granite or crecto models.

**Comment by drhuffman12** [comment] 2017-11-25 00:16
@drujensen and @elorest , thanks. I'll check adding a model or removing the migrate docker.

**Comment by drujensen** [comment] 2017-11-25 00:25
@drhuffman12 sounds good.  I'm going to close this issue.  You can re-open it if you find that this didn't solve it for you.

**Closed by drujensen** 2017-11-25 00:25 UTC

**Comment by clarkyi** [comment] 2019-02-18 11:14
I has same question 
amber version 0.11.3
run the command
`amber db create`                                                                                                                                                       
output 'packet 254 not implemented'
