### ISSUE TITLE
Support for crystal 1.4.0

### ISSUE THREAD

**Issue by backward-crazy-mage-puppy-36** [amberframework/amber#1276] opened 2022-04-10 08:02 UTC
Creating a new amber app with crystal v 1.4.0 and amber -v 1.2.1 and generating a table for authentication 
amber g auth User
When amber w results in
There was a problem expanding macro 'column'

Code in macro 'timestamps'

 2 | column updated_at : Time?
     ^
Called macro defined in lib/granite/src/granite/columns.cr:63:3

 63 | macro column(decl, **options)

Which expanded to:

 > 14 |
 > 15 |
 > 16 |     @[Granite::Column(column_type: nil, converter: nil, auto: false, primary: false, nilable: true)]
            ^
Error: can't annotate @updated_at in User because it was first defined in Granite::Base

**Comment by VanyaNeytrino** [comment] 2022-05-13 14:38
how to understand what is the cause of the bug? I looked at the sources and it's not clear at all. Does anyone have any thoughts on this?

**Comment by drujensen-happymoney** [comment] 2022-05-13 23:50
Looks like you `can't annotate @updated_at in User because it was first defined in Granite::Base`

Consider removing the `updated_at` column from the User class since it's already defined in the Base class.

**Comment by VanyaNeytrino** [comment] 2022-05-14 16:41
> Looks like you `can't annotate @updated_at in User because it was first defined in Granite::Base`
> 
> Consider removing the `updated_at` column from the User class since it's already defined in the Base class.

Thanks. I commented out the row `column update_at : Time?` in https://github.com/amberframework/granite/blob/master/src/granite/columns.cr#L108
would such a decision be normal?

**Comment by crimson-knight** [comment] 2022-05-17 23:12
This was an issue with Granite, I put up a PR that resolves this. Hopefully, it'll get merged in soon and you'll be good as gold!

**Comment by robacarp** [comment] 2022-05-18 17:09
https://github.com/amberframework/granite/pull/465 is merged now. If that fixes the issue please let us know!

**Comment by crimson-knight** [comment] 2022-05-24 20:12
@backward-crazy-mage-puppy-36 please run `brew upgrade amber` to get the latest version, and this issue will be resolved.

If any other issues arise, please create a new issue or join us on discord! :)

**Closed by crimson-knight** 2022-05-24 20:12 UTC
