### ISSUE TITLE
Cant build amber app

### ISSUE THREAD

**Issue by Iainmon** [amberframework/amber#1032] opened 2019-01-10 07:17 UTC
### Description

I can't build a brand new amber app.

### Steps to Reproduce

I just followed this guide:
https://docs.amberframework.org/amber/getting-started

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Amber CLI (amberframework.org) - v0.11.2

Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

### Additional Information
```
09:13:54 Watch run  | (INFO) Building...
Error in src/blogsy.cr:1: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:1: while requiring "./database.cr"

require "./database.cr"
^

in config/database.cr:5: undefined method 'progname=' for Nil (compile-time type is (Logger | Nil))

Granite.settings.logger.progname = "Granite"
                        ^~~~~~~~

Rerun with --error-trace to show a complete error trace.
09:13:55 Watch run  | (INFO) Compile time errors detected, exiting...
```

**Comment by jackturnbull** [comment] 2019-01-10 15:14
I believe this is only an issue until the next release - I hit the same issue recently too. The project you generated it valid apart from a couple of lines, the one listed in the stacktrace you posted and another in spec_helper.

Try replicating the changes made in https://github.com/amberframework/amber/pull/1027 with your generated files and that should get you up and running again.

**Comment by drujensen** [comment] 2019-01-12 16:51
@elorest Can you do a release of Amber?

**Comment by Metallord** [comment] 2019-01-13 00:32
Seems to be still present in 0.11.3. I work around it by changing the offending line to `Granite.settings.logger.try &.progname = "Granite"` Not sure if that's the correct approach, but it makes the build go through.

**Comment by drujensen** [comment] 2019-01-13 02:48
@Metallord Can you confirm you ran `shards update`?

**Comment by Metallord** [comment] 2019-01-13 09:36
```
Using amber (0.11.3)
Using amber_router (0.2.1)
Using cli (0.7.0)
Using optarg (0.5.8)
Using callback (0.6.3)
Using string_inflection (0.2.1)
Using compiled_license (0.1.3)
Using kilt (0.4.0)
Using liquid (0.3.0)
Using inflector (0.1.8)
Using micrate (0.3.3)
Using db (0.5.1)
Using mysql (0.5.1)
Using pg (0.15.0)
Using redis (2.0.0)
Using pool (0.2.3)
Using shell-table (0.9.2 at 078a04ea58ead5203bb435a3b5fff448ddabaeea)
Using slang (1.7.1)
Using sqlite3 (0.10.0)
Using teeplate (0.7.0)
Using exception_page (0.1.1)
Using granite (0.15.2)
Using quartz_mailer (0.5.3)
Using email (0.3.2)
Using jasper_helpers (0.2.4)
Using citrine-i18n (0.3.2)
Using i18n (0.2.0)
Using garnet_spec (0.2.1)
Using selenium (0.4.0)
lord@MacBook Pro ~/code/comms $ amber watch
10:35:21 Watch run  | (INFO) Building...
Error in src/comms.cr:1: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:1: while requiring "./database.cr"

require "./database.cr"
^

in config/database.cr:5: undefined method 'progname=' for Nil (compile-time type is (Logger | Nil))

Granite.settings.logger.progname = "Granite"
                        ^~~~~~~~

Rerun with --error-trace to show a complete error trace.
10:35:22 Watch run  | (INFO) Compile time errors detected, exiting...
```

**Comment by faustinoaq** [comment] 2019-01-19 15:06
Hi @Metallord Do you still have this issue?

This issue was introduced on v0.11.2. I can't reproduce it on v0.11.3

I guess this was fixed on latest version

BTW, v0.11.3 is now available on AUR, sorry for late update :sweat_smile:

https://aur.archlinux.org/packages/amber/

**Comment by nsuchy** [comment] 2019-05-07 21:01
@faustinoaq Looks like this issue can be closed unless @Iainmon can reproduce this bug on the latest version of Amber.

**Closed** 2019-05-20 02:41 UTC
Labels: kind:bug
