### ISSUE TITLE
Reduce Amber Repo Size

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#389] opened 2017-11-14 04:53 UTC
### Description

I was easily able to get amber down to under 1 MB and push it up to a test repo. In order clean up this repo we need to take a few steps.

1. Delete all old branches.
2. Close all open PR's.
3. Ideally deleting all Tags and recreating afterwards are necessary to really clean up. (This could cause problems though)

**Comment by eliasjpr** [comment] 2017-11-14 13:31
This is a duplicate of https://github.com/amberframework/amber/issues/334

**Comment by elorest** [comment] 2017-11-14 16:41
The other issue was a comment on the size of Amber. This issue is about how and what to fix.

**Comment by eliasjpr** [comment] 2017-11-14 17:36
Closing the other issue. Either issue can be tracked in one place.

**Comment by faustinoaq** [comment] 2017-11-18 04:13
Done!

**Closed by faustinoaq** 2017-11-18 04:13 UTC
Labels: duplicate
