### ISSUE TITLE
Add asset_path helper

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#881] opened 2018-06-20 19:34 UTC
### Description

An asset helper was tried to implement on #574

Amber have changed and now the PR have some big incompatibilitites

Also We're implementing #865 to fix #476 

All these changes are great and I still think `asset_path("path_to_asset")` is a great idea, so I opened this issue to track this feature and open a new PR in the future.

### Steps to Reproduce

Not applicable

### Versions

Amber master (https://github.com/amberframework/amber/commit/370f68effb087439f894bfd44400ba3178639a77)

### Additional Information

Thanks again to @JoshJuncker and @paulcsmith ! :tada: :100:

**Comment by drujensen** [comment] 2018-12-24 20:37
duplicate of #555

**Closed by drujensen** 2018-12-24 20:37 UTC
Labels: kind:feature, status:to-do
